name: E2E tests
on:
  push:
    branches:
      - master
      - qa
      - production
      - 'upgrade-3'
      - 'cap-next-cloud'
  pull_request:
    branches:
      - qa
      - production
jobs:
  Cypress:
    name: Cypress
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout to Code

      - name: Run docker-compose stack
        run: docker-compose -f docker-compose.e2e.yml up -d

      - name: Create DB
        run: |
          docker-compose -f docker-compose.e2e.yml run web-api cap db destroy --yes-i-know
          docker-compose -f docker-compose.e2e.yml run web-api cap db init
          docker-compose -f docker-compose.e2e.yml run web-api cap alembic upgrade heads
          docker-compose -f docker-compose.e2e.yml run web-api cap cap files location local var/data --default
          docker-compose -f docker-compose.e2e.yml run web-api cap fixtures schemas
          docker-compose -f docker-compose.e2e.yml run web-api sh scripts/create-demo-users.sh

      - name: Sleep for 180 seconds
        run: sleep 180s
        shell: bash

      - name: Run Cypress
        run: docker-compose -f docker-compose.e2e.yml run cypress cypress run --headless

      - name: Generate test file
        run: docker-compose -f docker-compose.e2e.yml run -u root web-api cap fixtures generate-tokens

      - name: Test request from 'cap-client' container
        run: docker-compose -f docker-compose.e2e.yml run cap-client ./run-tests.sh --check-pytest-e2e
