name: Full
on:
  push:
    branches:
      - 'cap-next-cloud'
jobs:
  Cypress:
    name: Cypress
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout to Code

      - name: Run docker-compose stack
        run: docker-compose -f docker-compose.full.yml up -d

      - name: Create DB
        run: |
          docker-compose -f docker-compose.full.yml run web-api cap db destroy --yes-i-know
          docker-compose -f docker-compose.full.yml run web-api cap db init
          docker-compose -f docker-compose.full.yml run web-api cap alembic upgrade heads
          docker-compose -f docker-compose.full.yml run web-api cap cap files location local var/data --default
          docker-compose -f docker-compose.full.yml run web-api cap fixtures schemas
          docker-compose -f docker-compose.full.yml run web-api sh scripts/create-demo-users.sh

      - name: Sleep for 180 seconds
        run: sleep 180s
        shell: bash

      - name: Run Cypress
        run: docker-compose -f docker-compose.full.yml run cypress cypress run --headless

      - name: Pytest
        run: docker-compose -f docker-compose.full.yml run web-api ./run-tests.sh --check-pytest
